"""Guard the hand-written capability totals against the generated matrix.

``docs/capability-gap-matrix.md`` is generated by
``scripts/report_capability_gaps.py``, so its Total row is the derivation of
record for how the platform API backend catalog splits across read /
diagnostic / write / destructive. Prose elsewhere restates that split, and
prose does not regenerate: ``docs/optional-products.md`` carried 3,156 read
tools while the matrix derived 3,159 for the same 6,711 total.

Pinning prose to the matrix is only worth anything if the matrix itself is
fresh. That is asserted against the committed file by
``tests/unit/test_capability_gap_report.py::test_the_committed_matrix_file_is_not_stale``
-- not by any workflow naming the script, which none do; CI reaches
``--check`` only indirectly through ``scripts/validate_release.py``, and
only after the unit suite has already passed.

So every restatement is pinned to the Total row rather than re-typed here,
and the Total row is itself anchored to ``docs/project-facts.json``'s
``tools.platform_backend_total`` so a mis-parse cannot pass quietly. There is
no canonical per-capability fact in ``project-facts.json`` -- ``read`` exists
only as the generated matrix column -- and inventing a second one would
recreate the drift this module exists to catch.

Dated release-notes snapshots are excluded: they record the catalog at
release time and must stay frozen.
"""

from __future__ import annotations

import re
from pathlib import Path

from hpe_networking_mcp.pipeline import project_facts

REPO_ROOT = Path(__file__).resolve().parents[2]
MATRIX_PATH = REPO_ROOT / "docs" / "capability-gap-matrix.md"

#: Shipped documentation only. Dot directories hold tooling and agent scratch
#: notes that quote these figures while discussing them, and build/ and dist/
#: hold stale copies of the very docs under test.
_EXCLUDED_TOP_LEVEL_DIRS = {"build", "data", "dist", "node_modules", "outputs"}


def _int(text: str) -> int:
    return int(text.replace(",", "").replace("*", "").strip())


def _matrix_totals() -> dict[str, int]:
    """The generated Total row, read by column heading rather than position."""
    header: list[str] | None = None
    for line in MATRIX_PATH.read_text(encoding="utf-8").splitlines():
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if header is None:
            if "Platform" in cells and "Read" in cells:
                header = cells
            continue
        if cells[0] == "**Total**":
            return {
                name: _int(value)
                for name, value in zip(header, cells, strict=True)
                if value.replace(",", "").replace("*", "").strip().isdigit()
            }
    raise AssertionError(f"{MATRIX_PATH} has no Total row to derive from")


TOTALS = _matrix_totals()
READ_TOOLS = TOTALS["Read"]
EXECUTABLE_TOTAL = TOTALS["Executable total"]

#: Whitespace-normalized so a claim may wrap across Markdown lines.
_ANNOTATED_COUNT = re.compile(
    r"backend catalog contains ([\d,]+) read-only-annotated tools "
    r"and ([\d,]+) registered"
)
_CAPABILITY_SPLIT = re.compile(
    r"([\d,]+) read, ([\d,]+) diagnostic, ([\d,]+) write, (?:and )?([\d,]+) destructive"
)
_CATALOG_ROW = re.compile(
    r"\| \*\*Platform API backend total\*\* \| \*\*([\d,]+)\*\* \| \*\*([\d,]+)\*\* \|"
)


def _current_doc_files() -> list[Path]:
    docs = []
    for path in sorted(REPO_ROOT.rglob("*.md")):
        rel = path.relative_to(REPO_ROOT)
        if rel.parts[0] in _EXCLUDED_TOP_LEVEL_DIRS or rel.parts[0].startswith("."):
            continue
        if rel.name.startswith("release-notes-") or path == MATRIX_PATH:
            continue
        docs.append(path)
    return docs


def _normalized_docs() -> list[tuple[Path, str]]:
    return [
        (path, " ".join(path.read_text(encoding="utf-8").split()))
        for path in _current_doc_files()
    ]


def test_the_matrix_total_row_still_describes_the_tracked_catalog():
    """Anchor the parse: a misread Total row must not silently pass."""
    tracked = project_facts.load()["tools"]

    assert EXECUTABLE_TOTAL == tracked["platform_backend_total"]
    assert TOTALS["Curated tools"] == tracked["platform_curated_total"]
    assert TOTALS["Active generated tools"] == tracked["generated_registered"]
    assert 0 < READ_TOOLS < EXECUTABLE_TOTAL


def test_prose_read_only_annotation_counts_match_the_generated_matrix():
    checked = []
    for path, text in _normalized_docs():
        for read, registered in _ANNOTATED_COUNT.findall(text):
            assert (_int(read), _int(registered)) == (READ_TOOLS, EXECUTABLE_TOTAL), (
                f"{path.relative_to(REPO_ROOT)} states {read} read-only-annotated "
                f"of {registered} registered platform API tools; "
                f"docs/capability-gap-matrix.md's Total row derives "
                f"{READ_TOOLS:,} of {EXECUTABLE_TOTAL:,}"
            )
            checked.append(path)

    assert checked, "no doc states the read-only-annotated count -- pattern stale?"


def test_prose_capability_splits_match_the_generated_matrix():
    checked = []
    for path, text in _normalized_docs():
        for read, diagnostic, write, destructive in _CAPABILITY_SPLIT.findall(text):
            stated = tuple(_int(value) for value in (read, diagnostic, write, destructive))
            derived = (
                READ_TOOLS,
                TOTALS["Diagnostic"],
                TOTALS["Write"],
                TOTALS["Destructive"],
            )
            assert stated == derived, (
                f"{path.relative_to(REPO_ROOT)} states capability totals {stated}; "
                f"docs/capability-gap-matrix.md's Total row derives {derived}"
            )
            checked.append(path)

    assert checked, "no doc states the capability split -- pattern stale?"


def test_the_tool_catalog_backend_total_row_matches_the_generated_matrix():
    checked = []
    for path, text in _normalized_docs():
        for read, registered in _CATALOG_ROW.findall(text):
            assert (_int(read), _int(registered)) == (READ_TOOLS, EXECUTABLE_TOTAL), (
                f"{path.relative_to(REPO_ROOT)}'s Platform API backend total row "
                f"states {read} read of {registered}; the generated matrix derives "
                f"{READ_TOOLS:,} of {EXECUTABLE_TOTAL:,}"
            )
            checked.append(path)

    assert checked, "no doc carries the Platform API backend total row -- format changed?"
